import React from 'react';
import StepImage from '../../ui/StepImage';

const ScaleSection = () => {
  return (
    <div className="bg-gray-50 p-6 rounded-xl">
      <div className="flex items-start gap-4">
        <span className="flex-shrink-0 w-8 h-8 bg-sirio-blue text-white rounded-full flex items-center justify-center font-semibold">6</span>
        <div>
          <h3 className="text-xl font-semibold text-gray-900 mb-4">Scale</h3>
          <p>The scale is the weight of the LoRA, in this case, your Digital Model.</p>
          
          <StepImage 
            src="https://i.ibb.co/k1Nm36r/Scale.png"
            alt="Scale Interface"
          />

          <div className="mt-4 mb-6">
            <p className="text-gray-600">
              The weight or scale determines how much of your custom model's features and style are applied 
              to the final portrait generated by the AI.
            </p>
          </div>

          <div className="bg-white border border-gray-200 rounded-xl overflow-hidden">
            <div className="p-4 border-b border-gray-100">
              <h4 className="font-semibold text-gray-900">Understanding Scale Values</h4>
            </div>

            <div className="divide-y divide-gray-100">
              <div className="p-4">
                <div className="flex items-center justify-between mb-3">
                  <span className="font-medium text-gray-900">Scale 0.5</span>
                  <span className="px-2.5 py-1 bg-gray-100 text-gray-600 rounded-full text-xs font-medium">
                    Light Influence
                  </span>
                </div>
                <p className="text-sm text-gray-600">
                  The influence of your custom LoRA model is lighter. The AI-generated portrait will have some 
                  features of your custom model, like maybe your hairstyle or facial shape, but it won't be a 
                  perfect match.
                </p>
              </div>

              <div className="p-4">
                <div className="flex items-center justify-between mb-3">
                  <span className="font-medium text-gray-900">Scale 1.0</span>
                  <span className="px-2.5 py-1 bg-sirio-blue/10 text-sirio-blue rounded-full text-xs font-medium">
                    Standard Strength
                  </span>
                </div>
                <p className="text-sm text-gray-600">
                  Your model's influence is at standard strength. The portrait will closely resemble the features 
                  and style you trained the model on—essentially capturing your likeness as intended. This means 
                  the AI uses your model fully to create a portrait that looks exactly like you, based on the 
                  data you provided.
                </p>
              </div>

              <div className="p-4">
                <div className="flex items-center justify-between mb-3">
                  <span className="font-medium text-gray-900">Scale 1.2+</span>
                  <span className="px-2.5 py-1 bg-sirio-yellow/10 text-sirio-yellow rounded-full text-xs font-medium">
                    Enhanced Features
                  </span>
                </div>
                <p className="text-sm text-gray-600">
                  The influence of your custom model becomes even stronger. The portrait will emphasize your unique 
                  features more dramatically. This could exaggerate certain characteristics, making the portrait 
                  more stylized or artistic, highlighting details like expressions or specific facial features 
                  even more than you trained for.
                </p>
              </div>
            </div>
          </div>

          <div className="mt-6 space-y-4">
            <div className="p-4 bg-sirio-blue/5 rounded-lg border border-sirio-blue/10">
              <p className="text-sm text-gray-600">
                <span className="font-medium text-sirio-blue">Understanding Scale:</span>{' '}
                The scale is like a dial that lets you control how much of your custom LoRA model's influence 
                you want in your AI-generated portrait. A higher scale makes the portrait look more like you, 
                based on the model you trained, while a lower scale keeps it closer to the original style.
              </p>
            </div>

            <div className="p-4 bg-sirio-yellow/5 rounded-lg border border-sirio-yellow/10">
              <p className="text-sm text-gray-600">
                <span className="font-medium text-sirio-yellow">Pro Tip:</span>{' '}
                Experiment with the weight of the LoRA. For me, I use 1.2 or 1.3 to achieve great results. 
                This sweet spot enhances your unique features while maintaining natural-looking results.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ScaleSection;